on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install --ignore-scripts
      - run: npm run build
      - run: npm run lint
      - run: git diff --exit-code